config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://main--minionfells.netlify.app'
  site_title: Rosh Suryawanshi
  site_subtitle_1: Portfolio - 2024
  site_subtitle_2: ''
  site_description: >
    Rosh Suryawanshi is a photographer, graphic designer and video editor based
    in Pune, MH.
  site_email: rxshan@pm.me
  site_social_url: 'https://ro-sh.com'
  site_icon_svg: /assets/uploadsassets/icons/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Portfolio | 2024
    site_description: ''
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#3000FF'
    background_dark: '#101010'
    text_dark: '#c1c1c1'
    link_dark: '#ffffff'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: false
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  jpeg:
    enabled: true
    quality: 75
  webp:
    enabled: true
    quality: 75
  avif:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Contact
